fail: first attempt to implement convert_to_tree to pass the spec
Prompt: Very good. Now we are in implementation mode. Here is the rspec failure I got:

F

Failures:

  1) convert_to_tree converts a vector into an n-ary tree
     Failure/Error: expect(convert_to_tree(vector)).to eq(tree)

     NoMethodError:
       undefined method `convert_to_tree' for #<RSpec::ExampleGroups::ConvertToTree "converts a vector into an n-ary tree" (./convert_to_tree_spec.rb:5)>
     # ./convert_to_tree_spec.rb:6:in `block (2 levels) in <top (required)>'

Finished in 0.00329 seconds (files took 0.09672 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./convert_to_tree_spec.rb:5 # convert_to_tree converts a vector into an n-ary tree